name: Release on Pypi

# Disabled workflow in template. 
# To enable, exchange the commented blocks.
on:
  push:
# Disable the branches-ignore block:
    branches-ignore:
      - '**'
# Enable the tags block:
#    tags:
#      - '*'
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies and packages
      run: |
        python -m pip install --upgrade pip
        make install-dev-noprecommit
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        make upload-pypi-public